### ISSUE TITLE
Lib does not account for legacy bots/apps

### ISSUE THREAD

**Issue by Kowlin** [interactions-py/interactions.py#108]
Hey there, when trying this lib out on an old bot (3 years+) I've noticed that the bot is unable to do anything due the fact that the bot's User ID is not the same as its Application ID. So setting the user ID here sadly doesn't work for old bots.
https://github.com/eunwoo1104/discord-py-slash-command/blob/bbec2e0e109a8bcbd3d47206fb8651299e094d3b/discord_slash/http.py#L75

![image](https://user-images.githubusercontent.com/10947836/109421997-ef06da80-79d9-11eb-9665-0f4fd9cc2299.png)

**Comment by eunwoo1104** [comment]
Unfortunately, this won't be fixed due to:
- We can't call `discord.Client.application_info()` before `run()` function is called and discord.py doesn't provide any cached/requested `AppInfo` instance, which makes implementing this issue's fix complicated.
- We can add `app_id` option at `SlashCommand`, but implementing that will be another major changes due to `discord.Client.user` doesn't exist before `run()` function is called, plus possible breaking change(s).

I could fix this issue, but still it will require major changes just to support old applications.
