### ISSUE TITLE
Allow callback when creating manual commands with add_slash_command

### ISSUE THREAD

**Issue by Mayerch1** [interactions-py/interactions.py#143]
when creating a callback at runtime with `discord_slash.utils.manage_commands.add_slash_command` it's currently not possible to specify a callback method.

The only option I see is, to manually intercept `on_slash_command` and implementing the mapping by myself.
However this is not very convenient when trying to handle some dynamic elements with the command interface.

Would it be possible to add a callback parameter?
It should behave the same way as using `@cog_ext.cog_slash`, in regards of calling the specified method.

**Comment by artem30801** [comment]
Probably you can achive same result with something like that, but I agee with request
```
callback = slash.slash(name="callback test",)(callback)
```

**Comment by quirky-bluejay** [comment]
`utils.manage_commands` **only** registers a command to the discord api. If you want to add a command to the local client to be invoked use [`SlashCommand.add_slash_command`](https://discord-py-slash-command.readthedocs.io/en/latest/discord_slash.client.html#discord_slash.client.SlashCommand.add_slash_command) as well as the function you were using

**Comment by i0bs** [comment]
[`SlashCommand.add_slash_command`](https://discord-py-slash-command.readthedocs.io/en/latest/discord_slash.client.html#discord_slash.client.SlashCommand.add_slash_command) uses a different method of invocation that does not need to be necessarily replicated for the `@cog_ext.cog_slash` method, as that's a decorator called a declaration event of registering the slash command instead of creation.
