### ISSUE TITLE
[BUG] Library fails to reconnect sometimes

### ISSUE THREAD

**Issue by Swarkin** [interactions-py/interactions.py#1570]
### Library Version

5.10.0

### Describe the Bug

Library fails to reconnect to discord servers.

### Steps to Reproduce

Get disconnected by a zombied connection.
See *Traceback*

### Expected Results

I expect the library to reconnect to the discord servers.

### Traceback

https://swarkin.sentry.io/share/issue/4655a819220942e29ecdfaefcf5e97a2/

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
Reconnection bugs are... not exactly easy to fix, and may just be due to dips in internet - you should never rely on the reconnection logic working perfectly, and should have a process manager to restart the bot in the worst case scenario.

That being said, `TypeError: ConnectionState.wrapped_logger() missing 1 required positional argument: 'message'` is a very interesting error that suggests that something is going wrong there. With the error provided, it's impossible to say, but it's worth keeping in mind.

EDIT: found the issue for this specific error, as you can see below.
