### ISSUE TITLE
Possible bug with options

### ISSUE THREAD

**Issue by hpenney2** [interactions-py/interactions.py#16]
I have a simple command I'm trying to use for testing:
```python
allowedIds = [1234567890, 0987654321] # Not the actual list, just showing as an example.

@slash.slash(name="msg", description="Sends an anonymous message.", guild_ids=allowedIds,
             options=[create_option("message", "What you want the message to say", 3, True)])
async def _echo(ctx: SlashContext, message: str):
    embed = discord.Embed(title="Anonymous message",
                          description=message,
                          color=0xeb4034)
    await ctx.send(3, embeds=[embed]) # respond with a message, eating the user's input
```
When I try to run the command, no message is sent because an error occurs.
```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "C:\Users\hpenney2\PycharmProjects\SlashBot\venv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\hpenney2\PycharmProjects\SlashBot\venv\lib\site-packages\discord_slash\client.py", line 288, in on_socket_response
    args = self.process_options(ctx.guild, to_use["data"]["options"], selected_cmd["auto_convert"]) \
  File "C:\Users\hpenney2\PycharmProjects\SlashBot\venv\lib\site-packages\discord_slash\client.py", line 264, in process_options
    loaded_converter = converters[types[auto_convert[selected["name"]]]]
KeyError: 3
```
`3` is the option type I gave, as seen above.
If I remove the options (including the parameter, references to the parameter, and the `options` argument in the decorator), the command works fine.

I tried to figure out the issue by looking through the source code to no avail. Did I somehow screw up options, or is this a bug?
Thank you in advance.

**Comment by VCJames** [comment]
KeyError 3 is correct here.
`selected["name"]` is most likely `"message"`

`auto_convert` is a little more tricky, but in client.py line ~175ish:
```
        if options:
            # Overrides original auto_convert.
            auto_convert = {}
            for x in options:
                if x["type"] < 3:
                    raise Exception("Currently subcommand is NOT supported.")
                auto_convert[x["name"]] = x["type"]
```

We infer `auto_convert` maps keys to option name ("message") and values to int option type (3).
`auto_convert["message"]` is most likely `3`...

There is then a dictionary:
```
types = {
            "user": 0,
            "USER": 0,
            6: 0,
            "6": 0,
            "channel": 1,
            "CHANNEL": 1,
            7: 1,
            "7": 1,
            "role": 2,
            "ROLE": 2,
            8: 2,
            "8": 2
        }
```

Whatever gets selected from `types` is then called from the list of `converters = [guild.get_member, guild.get_role, guild.get_role]`. These are functions/types native to Discord.py and `converters()` is then called to create an instance of it.

The dictionary mentioned above makes a little more sense when you compare w/ the Discord docs (esp when you reference `< 3 raise Exception()` because we don't support 1 and 2 yet):
![image](https://user-images.githubusercontent.com/15795500/102453634-9c3c9a00-400a-11eb-9cfd-3400e35cc9d6.png)

Good for interop. But, not sure the better way to implement this. Not familiar with Discord.py's types or if it's better to just return the string outright..?

**Comment by hpenney2** [comment]
> `auto_convert["message"]` is most likely `3`...

That's correct, I print `slash.commands` at `on_ready`.

Anything I can do then? Or do I just have to wait until auto convert is fixed to work properly with strings, integers, and booleans (since it appears those aren't found in the `types` dict, which I assume is why a `KeyError` happens)

**Comment by eunwoo1104** [comment]
It looks like it needs some fix.

> Anything I can do then? Or do I just have to wait until auto convert is fixed to work properly with strings, integers, and booleans (since it appears those aren't found in the types dict, which I assume is why a KeyError happens)

I'll make sure it will be fixed at next release.

**Comment by eunwoo1104** [comment]
For now, can you not pass `options`? Since it was originally for planned next feature, `auto_register`. `str`, `bool`, `int` types are correctly passed without `auto_convert` or `options`.

**Comment by hpenney2** [comment]
If I don't pass `options`, the arguments don't seem to be registered with Discord (at least not while using my auto-register script I noted in #9), so I guess I'll just wait for the next release.

**Comment by eunwoo1104** [comment]
Fixed now, try using Github's version, it should work.

**Comment by hpenney2** [comment]
Unable to test at the moment, I will try in the morning.

**Comment by hpenney2** [comment]
I can confirm that options now works properly with strings as of commit 086e1c3.
![image](https://user-images.githubusercontent.com/24281994/102522714-3aa51b80-405c-11eb-86f1-fba0412e6b18.png)
