### ISSUE TITLE
[FEAT] Custom DuplicateCommandError exception

### ISSUE THREAD

**Issue by BnDLett** [interactions-py/interactions.py#1684]
### Problem Description

I'm currently developing a bot known as "Aurora Bot," which experiences outages once in a while. One of the primary causes has been `ValueError: Duplicate Command! 0::bot_statistics`. In order to handle this, I'll be required to catch a ValueError exception -- which can be an issue during future development as it could make future issues harder to diagnose.

### Proposed Solution

In order to solve this, a custom exception class can be made that inherits from the `ValueError` (or `Exception`) class. In this way, you're only catching that specific exception class and not other exceptions that could be using the `ValueError` class too. 

### Alternatives Considered

It is possible for me to print out the details of the exception that is received, at which I would be lying if I said that it had significant downsides -- however, I see it as possibly more convenient to have a custom exception class for the duplicate command error. 

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by AstreaTSS** [comment]
Why exactly do you want to catch this error in the first place? An error like this is meant to stop the bot.

**Comment by mifuyutsuki** [comment]
I've looked into your bot code since it's public. For the specific use case of restarting the bot, you might have better luck with letting the bot exit out with an error and use a process manager such as systemd, pm2, or Docker to automatically restart your bot.

The root issue here is that you're re-executing `bot.start()` (using an infinite loop) everytime the method exits due to a connection error. That leads to the 'Duplicate command!' error you're having since the `bot`'s internal list of commands is already populated by the first call to `bot.start()`. By rerunning the code whole and not just looping `bot.start()`, `bot` is instantiated from scratch, alleviating the issue you're currently having with your bot.

**Comment by AstreaTSS** [comment]
Closing due to its invalid status, then, regardless of further comments. As suggested, use a process manager to obtain a clean start on restart instead of using an infinite loop.
