### ISSUE TITLE
Cannot remove embeds nor components from a message

### ISSUE THREAD

**Issue by Coryf88** [interactions-py/interactions.py#228]
[`ComponentContext.edit_origin`](https://github.com/discord-py-slash-commands/discord-py-interactions/blob/83937fefc297c3062c018381ef5c7751225b5d9b/discord_slash/context.py#L369) and `SlashMessage.edit` ([`SlashMessage._slash_edit`](https://github.com/discord-py-slash-commands/discord-py-interactions/blob/a7f468b66137726a2535a9d62177f6e25a8f8d2f/discord_slash/model.py#L492)) do not support using an empty list `[]` for the `embeds` nor `components` keyword argument, which prevents removing them from a message.

**Comment by AstreaTSS** [comment]
Going to add onto this - this seems to be due to how the library check for equality and the existence of kwargs. Empty lists are falsey values in Python, and since the library does `if kwarg.get("kwarg")` in order to see if a kwarg exists, this means that even if the kwarg exists, since [] is falsey, the library also mistakenly thinks it's false and so doesn't exist.

This can be solved simply by using `is not None` for those checks instead, Might make the PR myself to fix this, who knows.
