### ISSUE TITLE
Feature Request: Reply Slash Commands

### ISSUE THREAD

**Issue by Jerry-py** [interactions-py/interactions.py#267]
I've seen slash commands but when I reply to someone, the slash commands doesn't appear. I'll use dank memer as a example:

No reply:
![](https://i.imgur.com/dAd7C7f.gif)

Reply:
![](https://i.imgur.com/Wlt0M6x.gif)

Solution:
```
@slash.slash(name="test", reply_to_message=True)
```

Default set to `false`

**Comment by Catalyst4222** [comment]
You can't reply to a message and use a slash command due to how discord handles them. Slash command "messages" (the "X used Y") aren't true messages, and as a result they don't have everything standard messages do. This library can't enable that, because things would need to be changed in discord's side

**Comment by Jerry-py** [comment]
I'll end this with a `wontfix` (if i can) due to that I can't be worked on and isn't possible rn
