### ISSUE TITLE
Event removed in discord.py v2.

### ISSUE THREAD

**Issue by FightMan01** [interactions-py/interactions.py#306]
Not much needed here. They just removed the `on_socket_response` event.

**Comment by Toricane** [comment]
Yes, we knew that from a long time ago. For now, v3 and lower are incompatible with discord.py's 2.0, but the lib devs are working hard at creating a v4 that will be compatible, check #planned in the Discord for more details

**Comment by i0bs** [comment]
Would recommend watching the progress of the `unstable` branch for now. We're currently working on making discord-interactions an API wrapper for Discord (pending to become official, we're still in talks with Discord Staff about it) so this means we will be stepping away completely from any internal discord.py logic. The current internal scheme has our own gateway connection which essentially removes any incessant need to listen from `on_socket_response`. Because of this discord.py 2.0 and our library will both be able to run normally when v4.0 launches.
