### ISSUE TITLE
[REQUEST] Subcommands

### ISSUE THREAD

**Issue by Toricane** [interactions-py/interactions.py#411]
**What is the feature you're proposing?**
I would really like it if we could introduce subcommands into this library.
Currently, the only way to make subcommand is via this code:
```py
@bot.command(
    name="base",
    description="A simple subcommand",
    scope=874781880489222154,
    options=[
        interactions.Option(
            type=interactions.OptionType.SUB_COMMAND_GROUP,
            name="sub_command_group",
            description="A subcommand group",
            options=[
                interactions.Option(
                    type=interactions.OptionType.SUB_COMMAND,
                    name="sub_command",
                    description="A subcommand",
                )
            ],
        )
    ],
)
async def overcomplicated_subcommand(
    ctx: interactions.CommandContext, sub_command_group, sub_command
):
    await ctx.send("hey")
```
While this does work, there are three main issues with it, from lowest priority to the highest:
1. Requires extra arguments or keyword arguments in the function that are exactly named `sub_command_group` and/or `sub_command` in order to work
2. Overcomplicated approach of creating a subcommand, which is not easy to use
3. This is the most important dilemma; you can't have multiple subcommands with the same base.
    - When you try to make multiple of them with the same base, they are synchronized in a way that only registers the last subcommand, and unregisters the previous ones with the same base.
    - Another issue is that for example, when you do `print(bot.websocket.dispatch.events)`, you would get something like this: `{..., "command_base": [<function>, <function2>, ...], ...}`. The functions are the different subcommands for the same base, and when the subcommand is invoked, *all* of the functions are called one after the other.
    - This issue would need some of the synchronization and dispatching to be modified to allow multiple subcommands with the same base to be registered to the API and actually work.

I think that the code for creating the slash commands should be something like this:
```py
@bot.subcommand(
    base="base",
    subcommand_group="sub_command_group",  # this can be optional
    name="sub_command",
    description="A simple subcommand",
    scope=874781880489222154,
)
async def simple_subcommand(ctx: CommandContext):
    await ctx.send("hey")
```
I have implemented a decorator that makes the above code example work over [here](https://github.com/Toricane/better-interactions/blob/9b33a97f856beb2a76eb50b9a3d32ef79f6efa2b/interactions/ext/better_interactions/subcomand.py#L13), but it only solves the first two issues and does not resolve the third and most important one, where you can't have multiple subcommands with the same base.

**Additional Information**
- [ ] My feature request is related to an existing Issue.
    - Issue (if referenceable):

**Comment by i0bs** [comment]
I will be adding @DeltaXWizard to this card since they are co-developing the library with me. What I'll be saying below is my opinion and not tied to his.

I am **against** the idea of a `@subcommand` decorator or the likes. There are a few reasons that I want to get into why I'm stubborn about this, which I'll go over individually:

1. It's nothing more than an alias of `@command`.
2. It does not respect top-down level design of how subcommands work in the API.
3. It involves us changing a huge portion of the synchronization logic, as these would be wrapped differently dependent on the arguments.
4. Subcommands are inherently an option type for regular commands, and should be respected as such.

### It's nothing more than an alias of `@command`.

This one is pretty self-explanatory. Aliasing is something [we] avoided in version 4.0 because of how it creates confusion. Aliasing, for the most part, is a very nice thing to have because it adds further levels of abstraction to code. But, the major downside to aliasing is that if there comes a breaking change with the way that what we're abstracting off of is used, we have to change that too. On a low scale this is pretty trivial but the more we add aliases of certain features, the more we have to change aspects of the codebase. This also further increases the technical debt level which we ultimately wish to prevent and mitigate to the best of our abilities.

### It does not respect top-down level design.

Subcommands are a top-down level design from command, to group, to the subcommand itself when sent to the API and registered. We're already handling the dispatching logic differently than a typical argument in our Gateway when contextualizing data and sending it back to the callback for the decorator to infer from. The decorator doesn't comply with how you actually *structure* a subcommand. If subcommands were somehow processed differently and weren't (in my opinion) as cancerous as the API makes you do it thus far, then I would view this differently.

### It involves us changing a huge portion of syncing code, and different wrapping.

Something versions 3.0 and under used was a `to_dict` method, which I believe Delta and I can strongly contest to being one of the worst things we've ever had to work with. We would potentially see something similar, and you're somewhat doing it but with the `ApplicationCommand` object as your payload in this case where you presented potential code to do this. It *does* work but the first two points you addressed are the only ones being resolved, as you mentioned; with the last one still requiring synchronisation code to change. We don't really want to re-touch that syncing code either because it works to the best state we were able to get it to, as well as being modular in the pretense that it can be copy-pasted to handle permissions which (hopefully) 4.1.0 will support.

### Subcommands are inherently an option type.

This ties back into the 1st point, but I'm very dead set and firm on this. It's an **option regulator** and not a different command declaration. The UX only formats the command differently which leads to a lot of confusion about how they should be handled in the first place. Debatably seeing that this not being done in 4.0 as 3.0 and below did, a universal decorator was preferred because it respected the API's strictness. I'm personally waiting for the UX to be more explanative through the collapsible menu approach that the Discord staff have talked about proceeding with doing, so that this confusion about how a subcommand really works in the first place can be put to rest.

What we can do instead is fix the issues that the decorator currently has processing numerous subcommands and groupings; and teach people about how to add use cases to handle which subcommand is triggered better. This is a matter of us providing a clearer UX approach to the client-facing side of the library, as well as us making our best compromise to following the API as closely as we can. The closer we follow the API, the easier *in theory* changes can be made because we're not adding higher levels of abstraction where the client is not often interacting. (such as internal methods)

I will leave this Issue for open discussion, but these are my thoughts on it.

**Comment by Starlight220** [comment]
All the examples here are of simple subcommands, but what about complex ones?
Assuming I have different subcommands with different options (number and/or type of options), how would I implement that in the single-`@command`-function way of v4?
As much as I dislike the `@subcommand` way of v3, it made situations like these rather simple.

**Comment by Toricane** [comment]
While strictly following the API is preferable, I think we should also think about the ease of use for bot developers that want to or are using this library.

In v3 (and below), subcommands were extremely easy to make because it made it so each subcommand gets its own function. This can prevent redundant if/elif/else checks trying to see what was invoked, and act accordingly.

For example, something in v3:
```py
@slash.slash(
    base="base",
    subcommand_group="group1"
    name="name1"
)
async def name1(ctx): ...

@slash.slash(
    base="base",
    subcommand_group="group1"
    name="name2"
)
async def name2(ctx): ...

@slash.slash(
    base="base",
    subcommand_group="group2"
    name="name3"
)
async def name3(ctx): ...

@slash.slash(
    base="base",
    name="name4"
)
async def name4(ctx): ...
```
would equate to this in v4:
```py
async def name1(ctx): ...
async def name2(ctx): ...
async def name3(ctx): ...
async def name4(ctx): ...

@bot.command(
    name="base",
    description="No description",
    options=[
        Option(
            type=2,
            name="group1",
            description="No description",
            options=[
                Option(type=1, name="name1", description="No description"),
                Option(type=1, name="name2", description="No description"),
            ],
        ),
        Option(
            type=2,
            name="group2",
            description="No description",
            options=[
                Option(type=1, name="name3", description="No description"),
            ],
        ),
        Option(
            type=1,
            name="name4",
            description="No description",
        ),
    ],
)
async def foo(ctx, sub_command_group, sub_command):
    # Method 1:
    functions = {"name1": name1, "name2": name2, "name3": name3, "name4": name4}
    await functions[sub_command](ctx)

    # Method 2:
    if sub_command == "name1":
        await name1(ctx)
    elif sub_command == "name2":
        await name2(ctx)
    elif sub_command == "name3":
        await name3(ctx)
    elif sub_command == "name4":
        await name4(ctx)
```
As you can see, this is not easy to use, and is more complicated than it needs to be.

> Subcommands are inherently an option type for regular commands, and should be respected as such.

While the API *does* say that subcommands are options, they are invoked as normal commands and are displayed differently from each other. Your point of waiting for the UX to be made more explanatory is reasonable, but I still don't think that subcommands are true options and will be.

I would prefer that subcommands are supported natively in this library. If not, then I really don't care since I got them working in an extension that I made, and I am waiting for v4.1 for it to be put to use.

**Comment by Toricane** [comment]
> All the examples here are of simple subcommands, but what about complex ones? Assuming I have different subcommands with different options (number and/or type of options), how would I implement that in the single-`@command`-function way of v4? As much as I dislike the `@subcommand` way of v3, it made situations like these rather simple.

Yeah that's another point that I did not think of, and another reason why subcommands are not true options; they are subcommands, like the name suggests, not an option of a command.

**Comment by i0bs** [comment]
Due to demand from numerous users from the Discord support server and UX reasons from here, we will be implementing feature converters to the 2022 roadmap, subsequently bringing `@subcommand` as a decorator.
