### ISSUE TITLE
[BUG] ctx.populate() loading options failed when empty list passed in

### ISSUE THREAD

**Issue by SamNuttall** [interactions-py/interactions.py#448]
**Describe the bug**
The `populate()` function does not make an API call when anything that doesn't equal to True is passed in. This results in Discord informing the user that the autocomplete failed rather than that no options were found.

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Import the module in Python.
2. Create a client variable for the library.
3. Create a slash command with an option that has autocomplete.
4. Create an autocomplete function which uses `ctx.populate()` and pass an empty list or string to it.

**What's normally expected**
The command author (user) is informed that no options were found.
![image](https://user-images.githubusercontent.com/36005283/150647155-dba65d2e-efab-463b-b255-d51d160c4107.png)

**What actually happened**
Instead, an error is presented which indicates that loading has failed, even if `ctx.populate()` is called.
![image](https://user-images.githubusercontent.com/36005283/150647215-1829a701-9633-40e2-91b2-825f53837d64.png)

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Comment by i0bs** [comment]
I think you're confusing the way that `ctx.populate()` actually functions. The UI errors are somewhat confusing on what happens when you're supplying an empty list. "Loading options failed" means that the dispatched call has failed, meaning that the HTTP request encompassing the interaction response to the autocomplete call from the Gateway did not work properly.

This is expected because you're supplying it as an empty list in the `populate()` method, which we do not handle well right now. The method is expected to always take a list of possible options for population of the choice range in autocompletion.

"No options match your search." is when the autocomplete call from the Gateway is successfully responded to as an interaction from the HTTP request. This means that the method did actually send something, because in this case it will be expecting for you to supply actual choices for the user to select.

**Comment by SamNuttall** [comment]
Thanks for your response. I did just presume that it would be possible to inform the user that their search didn't match any of the autocomplete options using the `populate()` method. I'll create a response manually in order to display "No options match your search" instead.

> "Loading options failed" means that the dispatched call has failed, meaning that the HTTP request encompassing the interaction response to the autocomplete call from the Gateway did not work properly.

I believe the options failed to load because the bot didn't respond within 3 seconds. An application response is not sent when passing an empty list as the function is, in essence, skipped.

I'll close this issue as it appears that what I thought to be a bug is intentional behaviour.

**Comment by SamNuttall** [comment]
Fixed, see #755
