### ISSUE TITLE
[BUG] Logger Conflicting w/ Discord.py Logger

### ISSUE THREAD

**Issue by SergeBakharev** [interactions-py/interactions.py#457]
**Describe the bug**
When running both dpy and interactions.py a number of events will cause interactions.py to have an exception handling exceptions. Sometimes this can prevent the interactions gateway from reconnecting during a connection loss: [Traceback](https://gist.github.com/SergeBakharev/61da49cfdb09764f06e92d590935aa51)

I believe this occurs because both both dpy and interactions.py both use the same logger names (eg both dpy and interactions use a logger called "gateway"), AND the custom CustomFormatter/handler being set by interactions in base.get_logger().

As per [Python documentation for the logging library](https://docs.python.org/3/howto/logging-cookbook.html#adding-handlers-other-than-nullhandler-to-a-logger-in-a-library):

> Configuring logging by adding handlers, formatters and filters is the responsibility of the application developer, not the library developer. If you are maintaining a library, ensure that you don’t add handlers to any of your loggers other than a NullHandler instance.

**Reproducing steps**
This can easily be reproduced using the example from the Interactions FAQs ([gist](https://gist.github.com/SergeBakharev/bf6993b1c651028363ba9b1b40c8be0a)) by joining a voice channel after starting the bot. Traceback in the gist comment

**What's normally expected**
In the above example I still expect interactions.py to log a fatal log record but I don't expect to have an exception occur during logging.

**What actually happened**
Traceback in the [gist](https://gist.github.com/SergeBakharev/bf6993b1c651028363ba9b1b40c8be0a)) comment

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [x] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

**Comment by SergeBakharev** [comment]
In an attempt to put in a interim fix I have found I can disable the interactions.py logger with:
```
import logging.config

logging.config.dictConfig({
        'version': 1,
        'disable_existing_loggers': True,
    })
```
after interactions.Client()._ready()s

However it's temporary until interactions.py calls base.get_logger() again.

**Comment by i0bs** [comment]
I will be labelling this as a **wontfix** because of the following reasons:

1. Getting more than one library to work with ours is expensive due to numerous websocket connections with the Gateway.
2. Making libraries run on the same event loop presents issues with event calling strategy -- information between libraries can be ran twice, and there's no way to reliably ensure protection against race conditions.
3. discord.py is currently labelled as an archived project. We'll be treating discord.py as deprecated from hereon forward due to the upcoming message intent eliminating the ability to use `discord.ext.commands`, the most used user-facing part of the API wrapper.
4. In `4.1.0` and forward, we'll be offering developers the `Extension` object which can be used akin to cogs.

Starting effectively on April 2022, we will be removing any and all documentation pertaining to running libraries on an event loop, or handling callable coroutines with this library.
