### ISSUE TITLE
auto_register=True does not work within cogs

### ISSUE THREAD

**Issue by EdwardChamberlain** [interactions-py/interactions.py#51]
Slash commands arent registered with discord when using `auto_register=True`.

Code to reproduce, running within a cog:

```
    def __init__(self, bot):
        self.bot = bot
     
        if not hasattr(bot, "slash"):
            bot.slash = SlashCommand(bot, auto_register=True, override_type=True)

        self.bot.slash.get_cog_commands(self)
 
    def cog_unload(self):
        self.bot.slash.remove_cog_commands(self)

    @cog_ext.cog_slash(name="Ping2")
    async def ping2(self, ctx: SlashContext):
        await ctx.send(content=f"Pong!")
```

With the above code, I would expect the command to register and be available to users, however, it is not.

Checking registered commands with:
```
    @commands.command()
    async def get_slash(self, ctx):
        print(self.bot.slash.auto_register)
        print("Showing Commands Registered:")
        for i in await discord_slash.utils.manage_commands.get_all_commands(id, token, ctx.guild.id):
            print(i)
```
Shows no registered commands.

Setting the command with:
```
    @commands.command()
    async def put_cmd(self, ctx):
        print("Setting Commands:")
        await discord_slash.utils.manage_commands.add_slash_command(id, token, ctx.guild.id, "Ping2", "Test")
```
successfully makes the command available to users and is visible when checking with the `get_slash` function above.

**Comment by spinnerich** [comment]
You should try adding a description to your decorator as you've done in the direct `manage_commands.add_slash_command()` call.

-> `@cog_ext.cog_slash(name="Ping2", description="Test")`

**Comment by EdwardChamberlain** [comment]
I have added a description with no change. Code is as follows:

```py
    def __init__(self, bot):
        self.bot = bot

        if not hasattr(bot, "slash"):
            bot.slash = SlashCommand(
                bot,
                auto_register=True,
                override_type=True,
                auto_delete=True,
            )

        self.bot.slash.get_cog_commands(self)
 
    def cog_unload(self):
        self.bot.slash.remove_cog_commands(self)

    @cog_ext.cog_slash(name="test_cmd", description="Test", guild_ids=[640522864214278155])
    async def _test_cmd(self, ctx: SlashContext):
        await ctx.send(content="I have not implemented this")
```
In this case, the command shows up **successfully** but only after a bot restart but not a cog reload. 

Adding an additional command to the cog: 
```py
    @cog_ext.cog_slash(name="testing", description="Testing", guild_ids=[640522864214278155])
    async def testing_cmd(self, ctx: SlashContext):
        await ctx.send(content="I have not implemented this")
```
and reloading the cog the first command is present but the new command is not. 

It seems that auto_register only runs register_all_commands on initialization and not on cog loads and unloads. Perhaps running whenever a cog is loaded/unloaded would be better behavior?

To work around this issue I have altered my init and unload functions like so: 
```py
    def __init__(self, bot):
        self.bot = bot

        if not hasattr(bot, "slash"):
            bot.slash = SlashCommand(
                bot,
                override_type=True,
            )

        self.bot.slash.get_cog_commands(self)
        self.bot.loop.create_task(self.bot.slash.register_all_commands()) #<-- Added to update commands on load
 
    def cog_unload(self):
        self.bot.slash.remove_cog_commands(self)
        self.bot.loop.create_task(self.bot.slash.delete_unused_commands()) #<-- Added to remove commands on unload
```

With this alteration commands now show up on cog load, and disappear on cog unload as expected.

**Comment by quirky-bluejay** [comment]
Just to clarify it seems like the issue here is that the commands are not registered when the cog is reloaded, not the entire bot reloaded.
I had a look at what `auto_register` actually does, and the problem is that the commands are only registered when the cog is first loaded.
The expected behaviour would be that it registered any new commands on cog reload.

We've managed at find a work around, calling `self.bot.loop.create_task(self.bot.slash.register_all_commands())` in `__init__` of the cog
But it would be good if the library registered them on reload itself (when `auto_register` is True

Note: there is the same issue with `auto_delete`


Oh oops sorry, the last comment was posted when I was writing this one and it didn't update :facepalm:

Edit(idea for solution):
Would changing auto register so that it registeres a command to discord, individually, when the command is added to `SlashCommand` work?

**Comment by eunwoo1104** [comment]
First of all, currently `auto_register` is originally called only once after `on_ready` is dispatched since this extension originally didn't support cogs properly, but it is now. I think there won't be any problems due to constant command register things, so supporting feature needed at this issue should have no problem.
I'll make sure automatic slash command register/delete on cog load/unload feature is added at maybe `1.0.9`.

**Comment by eunwoo1104** [comment]
Implemented, will be included at next release.
