### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by Yuvaraja28** [interactions-py/interactions.py#557]
**Discord has Released new Component**
Is it Possible to add this component to the library?
https://discord.com/developers/docs/interactions/message-components#text-inputs

**Comment by FayeDel** [comment]
Hiya!

This component (and the object using them) are already in this library, you can look at the [docs](https://discord-interactions.readthedocs.io/en/latest/models.component.html?highlight=modal#component-models) for more info.
If you need further assistance in this server, you're welcome to join the support server if you'd like,

Because this component's already in the library, I'm closing this issue. :)
