### ISSUE TITLE
[BUG] add_role() does not report an error when it doesn't have permission to set role

### ISSUE THREAD

**Issue by kkolyno** [interactions-py/interactions.py#594]
### Describe the bug.

add_role() function reports a clean return message with no error even when it doesnt successfully add the role. This can happen when the bot's role position is not higher than the role it is trying to set.

### List the steps.

How to reproduce:
set the bot to be the lowest position on the server, have it run add_role() to try and assign a role higher than its own. The library will return no errors, and the role will not be assigned.

Move the bot to a position higher than the role it is trying to assign, everything works fine.

### What you expected.

I expected the bot to kick back an error/warning saying it doesnt have permission to set the role due to its "role position"

### What you saw.

No output at all, and no assigned role

### What version of the library did you use?

stable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
👋🏼  The reason why we do not collect errors in our `HTTPClient` methods is because we're following endpoint parity with the listed endpoints of the Discord API. This is something you'll unfortunately need to do in your own bot code *before* assigning a role, in order to ensure that the role is properly assigned.

The latter would be editing the member `add_role` method to do this which I entertain anyone to PR if the desire is present.
