### ISSUE TITLE
[BUG] your invite link doesnt work

### ISSUE THREAD

**Issue by kz-n** [interactions-py/interactions.py#834]
### Describe the bug.

[ ](https://discord.com/invite/interactions)

### List the steps.

.

### What you expected.

.

### What you saw.

.

### What version of the library did you use?

release

### Version specification

.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Damego** [comment]
What the point of this issue? Close this and open new normal filled issue.

**Comment by Damego** [comment]
Invite link lol https://discord.gg/KkgMBVuEkx

**Comment by kz-n** [comment]
![immagine](https://user-images.githubusercontent.com/64893077/172873132-debdf372-0579-431e-98a8-56ff21d21894.png)

**Comment by FayeDel** [comment]
Hiya!

That invite link would normally work, except that we're granted that vanity because of discord boosts at the moment, and its not guaranteed (atm) that the boost URL will persist when boosts fluctuate.
With that said, I'm changing that link to a more persistent URL that Damego pointed above, and will close this issue ^^
